name: Deploy app on release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22" # or your required version

      - name: Build Go binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o gloom ./cmd/ui

      - name: Copy binary to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "gloom"
          target: "/home/gloom/gloom/" # wherever the binary should live

      - name: Restart service on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo systemctl stop ${{ secrets.SERVICE_NAME }}
            sudo setcap 'cap_net_bind_service=+ep' /home/gloom/gloom/gloom
            mv ~/gloom /home/gloom/gloom/gloom
            sudo systemctl start ${{ secrets.SERVICE_NAME }}
